name: codesystem

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Check codesystem
      uses: gofast-pkg/codesystem@main
      with:
        type: 'app'
        context: '.'
        ignored-files: '${{ vars.CODESYSTEM_IGNORED_FILES }}'